# Generated by Django 5.2.9 on 2026-05-04 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Trading date for this chat thread', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('ai', 'AI'), ('user', 'User')], max_length=10)),
                ('message_type', models.CharField(choices=[('morning_brief', 'Morning Brief'), ('intraday_alert', 'Intraday Alert'), ('personalized_insert', 'Personalized Insert'), ('user_message', 'User Message'), ('ai_response', 'AI Response')], max_length=25)),
                ('content', models.TextField()),
                ('trigger', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pivy_chat.chatday')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pivy_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
