# Generated by Django 5.2.9 on 2025-12-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(max_length=255, unique=True)),
                ('first_name', models.TextField(max_length=255)),
            ],
        ),
    ]
