# Generated by Django 5.2.9 on 2026-01-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_first_name_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='light', max_length=10),
        ),
    ]
