# Generated by Django 5.2.8 on 2026-01-17 01:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underlying_symbol', models.CharField(help_text='The underlying stock symbol (e.g., AAPL)', max_length=20)),
                ('option_type', models.CharField(choices=[('call', 'Call'), ('put', 'Put')], max_length=4)),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expiration_date', models.DateField()),
                ('contract_symbol', models.CharField(help_text='OCC option symbol (e.g., AAPL240119C00150000)', max_length=50, unique=True)),
                ('multiplier', models.IntegerField(default=100, help_text='Contract multiplier (typically 100 shares)')),
            ],
            options={
                'ordering': ['underlying_symbol', 'expiration_date', 'strike_price'],
                'unique_together': {('underlying_symbol', 'option_type', 'strike_price', 'expiration_date')},
            },
        ),
        migrations.CreateModel(
            name='OptionPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=5)),
                ('quantity', models.IntegerField(help_text='Number of contracts')),
                ('average_cost', models.DecimalField(decimal_places=4, help_text='Average premium paid/received per contract', max_digits=15)),
                ('current_price', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Current option premium', max_digits=15)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_positions', to='paper_trading.papertradingaccount')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='paper_trading.optioncontract')),
            ],
            options={
                'unique_together': {('account', 'contract', 'position_type')},
            },
        ),
        migrations.CreateModel(
            name='OptionStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strategy_type', models.CharField(choices=[('long_call', 'Long Call'), ('long_put', 'Long Put'), ('short_call', 'Short Call (Naked)'), ('short_put', 'Short Put (Cash-Secured)'), ('vertical_call', 'Vertical Call Spread'), ('vertical_put', 'Vertical Put Spread'), ('iron_condor', 'Iron Condor'), ('iron_butterfly', 'Iron Butterfly'), ('straddle', 'Straddle'), ('strangle', 'Strangle'), ('covered_call', 'Covered Call'), ('protective_put', 'Protective Put'), ('collar', 'Collar'), ('calendar', 'Calendar Spread'), ('diagonal', 'Diagonal Spread'), ('custom', 'Custom Strategy')], max_length=20)),
                ('underlying_symbol', models.CharField(max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_strategies', to='paper_trading.papertradingaccount')),
                ('legs', models.ManyToManyField(related_name='strategies', to='paper_trading.optionposition')),
            ],
        ),
        migrations.CreateModel(
            name='OptionTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('buy_to_open', 'Buy to Open'), ('sell_to_close', 'Sell to Close'), ('sell_to_open', 'Sell to Open'), ('buy_to_close', 'Buy to Close')], max_length=15)),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit')], default='market', max_length=10)),
                ('quantity', models.IntegerField(help_text='Number of contracts')),
                ('premium', models.DecimalField(decimal_places=4, help_text='Premium per share (not per contract)', max_digits=15)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total premium (quantity * premium * multiplier)', max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Commission/fees', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('expired', 'Expired'), ('assigned', 'Assigned'), ('exercised', 'Exercised')], default='filled', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_shares', models.IntegerField(blank=True, help_text='Number of shares assigned/exercised', null=True)),
                ('assignment_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_trades', to='paper_trading.papertradingaccount')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='paper_trading.optioncontract')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
