# Generated by Django 5.2.8 on 2026-01-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='Stock ticker symbol (e.g., AAPL)', max_length=10)),
                ('date', models.DateField(help_text='Date of the stock data')),
                ('open_price', models.DecimalField(decimal_places=2, help_text='Opening price', max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, help_text='Highest price', max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, help_text='Lowest price', max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, help_text='Closing price', max_digits=10)),
                ('volume', models.BigIntegerField(help_text='Trading volume')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
